stages:        
  - sync

sync_to_github:
  image: ubuntu:latest
  stage: sync
  script:
    - apt-get update -qy
    - apt-get install -y git   
    - cd /tmp
    - git clone https://github.com/twcc/openapidoc.git
    - cd openapidoc
    - git remote remove origin
    - git remote add origin https://${LEO_USERNAME}:${Leo_ACCESS_TOKEN}@github.com/twcc/openapidoc.git
    - git config user.email "leo.chen@twsc.io"
    - git config user.name "Leo"
    - git pull origin main --ff-only
    - pwd
    - cp -R $CI_PROJECT_DIR/. .
    - git add -A
    - git commit -m "Sync changes from GitLab CI/CD job $CI_JOB_ID"
    - git push origin main
