openapi: 3.0.0
info:
  version: 1.0.0
  title: LB update Listener
  description: ''
security:
  - ApiKeyAuth: []
servers:
  - description: production url
    url: https://apigateway.twcc.ai/api/v3/openstack-taichung-default-2/
  - description: staging url
    url: https://apigateway.twcc.tw/api/v3/openstack-taichung-default/
tags:
  - name: 主要
  - name: 參考API
paths: 
  /loadbalancers/:
    get:
      tags:
      - 參考API
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/get/summary'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/get/responses/200'
    post:
      tags:
      - 參考API
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/post/summary'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/post/parameters/0'
      requestBody:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/post/requestBody'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1/post/responses/200'
  /loadbalancers/{loadbalancer_id}/:
    get:
      tags:
      - 參考API
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1/get/summary'
      description:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1/get/description'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1/get/responses/200'
  /loadbalancers/{loadbalancer_id}/action/:
    put:
      tags:
      - 主要
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1action~1/put/summary'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1action~1/put/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1action~1/put/parameters/1'
      requestBody:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1action~1/put/requestBody'
      responses:
        202:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1loadbalancers~1{loadbalancer_id}~1action~1/put/responses/202'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  parameters:
  schemas: