openapi: 3.0.0
info:
  version: 1.0.0
  title: VCSi copy
  description: ''
security:
  - ApiKeyAuth: []
servers:
  - description: production url
    url: https://apigateway.twcc.ai/api/v3/
  - description: staging url
    url: https://apigateway.twcc.tw/api/v3/
tags:
  - name: 主要
  - name: 參考API
  - name: 其他
paths: 
  /image_requests/:
    get:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/responses/200'
    post:
      tags: 
        - 主要
      summary: 
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/summary'
      parameters: 
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/parameters/0'
      requestBody:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/requestBody'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/responses/200'
  /image_requests/{image_request_id}/:
    get:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/responses/200'
    delete:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/responses/204'
    patch:
      tags:
        - 其他
      summary: Agree Image Request
      parameters:
        - $ref: '#/components/parameters/ImageRequsetIDParam'
        - $ref: '#/components/parameters/ApiHostParam'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [approved, failed, finished, requested]
  /images/:
    get:
      tags:
        - 參考API
      summary: 
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/summary'
      servers:
      - $ref: '../../Main/yaml/VCS.yaml#/servers/0'
      - $ref: '../../Main/yaml/VCS.yaml#/servers/1'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/responses/200'
  /projects/:
    get:
      tags:
        - 參考API
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/summary'
      servers:
      - $ref: '../../Main/yaml/VCS.yaml#/servers/0'
      - $ref: '../../Main/yaml/VCS.yaml#/servers/1'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/responses/200'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  parameters:
    ImageRequsetIDParam:
      name: image_requset_id
      in: path
      description: image requset id
      required: true
      schema:
        type: integer
    ApiHostParam:
      name: x-api-host
      in: header
      description: 認證必要參數
      required: true
      schema:
        type: string
        default: goc
  schemas:
    ImageSerializer:
      required:
      - create_time
      - id
      - is_public
      - name
      - platform
      - server
      - status
      type: object
      properties:
        create_time:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        is_public:
          type: boolean
        name:
          type: string
        platform:
          type: string
        user:
          $ref: '#/components/schemas/UserSerializer'
        server:
          $ref: '#/components/schemas/ServerFieldSerializer'
        status:
          type: string
    ServerFieldSerializer:
      required:
      - hostname
      - id
      type: object
      properties:
        hostname:
          type: string
        id:
          type: integer
          format: int64
    UserSerializer:
      required:
      - display_name
      - email
      - id
      - username
      type: object
      properties:
        id:
          type: string
        display_name:
          type: string
        username:
          type: string
        email:
          type: string
    ImageRequests:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
          enum: [approved, failed, finished, requested]
        status_reason:
          type: string
        tag_image:
          type: string
        create_time:
          type: string
          format: date-time
        src_project:
          $ref: '#/components/schemas/ProjectInfo'
        dst_project:
          $ref: '#/components/schemas/ProjectInfo'
        image:
          $ref: '#/components/schemas/ImageInfo'
    ProjectInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        platform:
          type: string
    ImageInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        is_public:
          type: boolean
        name:
          type: string
        status:
          type: string
        create_time:
          type: string
          format: date-time
    PostImageRequests:
      type: object
      properties:
        image:
          description: 來源 image ID，於參考API中
          type: integer
        dst_project:
          description: 複製端 project ID
          type: integer
        tag_image:
          description: 複製端 image name
          type: string