openapi: 3.0.0
info:
  version: 1.0.1
  title: VCSi copy
  description: ''
security:
  - ApiKeyAuth: []
servers:
  - description: production url
    url: https://apigateway.twcc.ai/api/v3/
  - description: staging url
    url: https://apigateway.twcc.tw/api/v3/
tags:
  - name: 主要
  - name: 參考API
  - name: 其他
paths: 
  /image_requests/:
    get:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/1'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/2'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/parameters/3'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/get/responses/200'
    post:
      tags: 
        - 主要
      summary: 
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/summary'
      parameters: 
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/parameters/0'
      requestBody:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/requestBody'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1/post/responses/200'
  /image_requests/{image_request_id}/:
    get:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/get/responses/200'
    delete:
      tags:
        - 主要
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/delete/responses/204'
    patch:
      tags:
        - 其他
      summary:
        $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/patch/summary'
      parameters:
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/patch/parameters/0'
        - $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/patch/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/Common.yaml#/paths/~1image_requests~1{image_request_id}~1/patch/responses/200'
  /images/:
    get:
      tags:
        - 參考API
      summary: 
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1images~1/get/summary'
      servers:
      - $ref: '../../Main/yaml/VCS.yaml#/servers/0'
      - $ref: '../../Main/yaml/VCS.yaml#/servers/1'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1images~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1images~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1images~1/get/responses/200'
  /projects/:
    get:
      tags:
        - 參考API
      summary:
        $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/summary'
      servers:
      - $ref: '../../Main/yaml/VCS.yaml#/servers/0'
      - $ref: '../../Main/yaml/VCS.yaml#/servers/1'
      parameters:
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/0'
        - $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/parameters/1'
      responses:
        200:
          $ref: '../../Main/yaml/VCS.yaml#/paths/~1projects~1/get/responses/200'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  parameters:
  schemas: