swagger: '2.0'
info:
  version: '1.4.0910'
  title: TProof Deposit API
  description: An API for TProof Service.
host: tproof.twcc.ai
schemes:
  - https
basePath: /api/v1
produces:
  - application/json

paths:
  /tproof/deposit:
    post:
      summary: Deposit a TProof
      tags:
        - TProof
      parameters:
        - in: header
          name: accept
          required: true
          type: string
          default: application/json
        - in: header
          name: Content-Type
          required: true
          type: string
          default: application/json
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              apikey:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    signature:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
      responses:
        200:
          description: Successfully deposited
          schema:
            type: object
            properties:
              error:
                type: string
              data:
                type: array
                items:
                  type: string
        400:
          description: Bad Request
          schema:
            type: string
        401:
          description: Unauthorized
          schema:
            type: string

        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: Not Found
          schema:
            type: object
            properties:
              statusCode:
                type: integer
              error:
                type: string
              message:
                type: string
        422:
          description: Unprocessable Entity
          schema:
            type: string
        429:
          description: Too Many Requests
          schema:
            type: string
        502:
          description: Bad Gateway
          schema:
            type: string
        503:
          description: Service Unavailable
          schema:
            type: string

